### ISSUE TITLE
สนใจอยากลองไปใช้งาน แต่ไม่ค่อยเก่ง Coding 

### ISSUE THREAD

**Issue by kobdesign** [theduckdose/thai-smartcard-reader#8]
สนใจอยากลองไปใช้งาน แต่ไม่ค่อยเก่ง Coding พอมีตัวอย่างโปรแกรมให้ศึกษาเพิ่มเติมมั้ยครับ

**Comment by doctoraod** [comment]
@kobdesign https://github.com/doctoraod/example-citizen-card ลองตัวนี้ดูได้ครับ ^^ สงสัยตรงไหนปรึกษาได้

**Comment by kobdesign** [comment]
ขอบคุณมากๆ ครับ หากติดอะไรจะขอรบกวนด้วยนะครับ :)
